//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pz6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        public Clients()
        {
            this.Orders = new HashSet<Orders>();
            this.TableReservations = new HashSet<TableReservations>();
        }
    
        public int ClientID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string Phone { get; set; }
        public int AutID { get; set; }
    
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual UserAuthorization UserAuthorization { get; set; }
        public virtual ICollection<TableReservations> TableReservations { get; set; }
    }
}
