//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pz6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dishes
    {
        public Dishes()
        {
            this.OrderItems = new HashSet<OrderItems>();
            this.ProductDish = new HashSet<ProductDish>();
        }
    
        public int DishID { get; set; }
        public string DishName { get; set; }
        public decimal Price { get; set; }
        public int CookingTime { get; set; }
        public string Allergens { get; set; }
        public string NutritionalInfo { get; set; }
    
        public virtual ICollection<OrderItems> OrderItems { get; set; }
        public virtual ICollection<ProductDish> ProductDish { get; set; }
    }
}
