//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pz6.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RestaurantEntities : DbContext
    {
        public RestaurantEntities()
            : base("name=RestaurantEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Clients> Clients { get; set; }
        public DbSet<Dishes> Dishes { get; set; }
        public DbSet<Employees> Employees { get; set; }
        public DbSet<OrderItems> OrderItems { get; set; }
        public DbSet<Orders> Orders { get; set; }
        public DbSet<OrderStatus> OrderStatus { get; set; }
        public DbSet<Positions> Positions { get; set; }
        public DbSet<Procurements> Procurements { get; set; }
        public DbSet<ProcurementStatus> ProcurementStatus { get; set; }
        public DbSet<ProductDish> ProductDish { get; set; }
        public DbSet<Products> Products { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<TableReservations> TableReservations { get; set; }
        public DbSet<TableStatus> TableStatus { get; set; }
        public DbSet<Unit> Unit { get; set; }
        public DbSet<UserAuthorization> UserAuthorization { get; set; }
    }
}
