//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pz6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public Orders()
        {
            this.OrderItems = new HashSet<OrderItems>();
        }
    
        public int OrderID { get; set; }
        public int ClientID { get; set; }
        public int TableNumber { get; set; }
        public System.DateTime OrderDateTime { get; set; }
        public int Status { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual ICollection<OrderItems> OrderItems { get; set; }
        public virtual OrderStatus OrderStatus { get; set; }
    }
}
