//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pz6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Procurements
    {
        public int ProcurementID { get; set; }
        public int ProductID { get; set; }
        public int Quantity { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int Status { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual ProcurementStatus ProcurementStatus { get; set; }
    }
}
