//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pz6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDish
    {
        public int ProductID { get; set; }
        public int DishID { get; set; }
        public int UnitID { get; set; }
        public decimal Count { get; set; }
        public int ProductDishID { get; set; }
        public int ID { get; set; }
    
        public virtual Dishes Dishes { get; set; }
        public virtual Products Products { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
