//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pz6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public Products()
        {
            this.Procurements = new HashSet<Procurements>();
            this.ProductDish = new HashSet<ProductDish>();
        }
    
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public int CurrentStock { get; set; }
    
        public virtual ICollection<Procurements> Procurements { get; set; }
        public virtual ICollection<ProductDish> ProductDish { get; set; }
    }
}
