//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pz6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableReservations
    {
        public int ReservationID { get; set; }
        public int ClientID { get; set; }
        public int TableNumber { get; set; }
        public System.DateTime ReservationDateTime { get; set; }
        public int Status { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual TableStatus TableStatus { get; set; }
    }
}
