//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pz6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAuthorization
    {
        public UserAuthorization()
        {
            this.Clients = new HashSet<Clients>();
            this.Employees = new HashSet<Employees>();
        }
    
        public int ID { get; set; }
        public string Email { get; set; }
        public string HashPassword { get; set; }
    
        public virtual ICollection<Clients> Clients { get; set; }
        public virtual ICollection<Employees> Employees { get; set; }
    }
}
